[project]
name = "test-python-project"
description = "Test Python project with nixos"
version = "0.1.0"
authors = [
    { name = "chuanhao01", email = "test@email.com" }
]
dependencies = [
    "flask"
]
