[project]
name = "nixos-python-project-template"
version = "0.1.0"
description = "NixOS Python Project template using flakes and uv2nix"
requires-python = ">=3.12"
authors = [
    { name = "chuanhao01", email = "test@email.com" }
]
dependencies = []

[dependency-groups]
dev = [
    "ruff",
]
